import { Refeicao } from "./refeicao.model";


export interface AlimentoTaco  {
    id?: String,
    categoria?: String,
    numeroAlimento?: String,
    descricaoAlimento?: string,
    unidade?: String,
    energiaKcal?: string,
    energiaKj?: String,
    proteina?: string,
    lipideos?: string,
    colesterol?: String,
    carboidrato?: string,
    fibraAlimentar?: String,
    cinzas?: String,
    calcio?: String,
    magnesio?: String,
    fosforo?: String,
    ferro?: String,
    sodio?: String,
    potassio?: String,
    cobre?: String,
    zinco?: String,
    retinol?: String,
    re?: String,
    rae?: String,
    tiamina?: String,
    riboflavina?: String,
    piridoxina?: String,
    niacina?: String,
    vitamin?: String,
    created_at?: String,
    updated_at?: String,   
}